CLOUDP-126257: Create command 'atlas backups exports buckets describe'
mongodb/mongodb-atlas-cli pull request #1354
Opened 2022-07-07 10:22 UTC by Razeer123

## Proposed changes

I added the "atlas backups exports buckets describe" command to the CLI and a unit test to verify the correctness of the implementation.

_Jira ticket:_ [CLOUDP-126257](https://jira.mongodb.org/browse/CLOUDP-126257)

## Command syntax and output

```
michal.derej@M-L7H6RDJWQX mongodb-atlas-cli % ./bin/atlas backup exports buckets describe --bucketId 62c569f85b7a381c093cc539 -P dev
ID                         BUCKET NAME          CLOUD PROVIDER   IAM ROLE ID
62c569f85b7a381c093cc539   michal-test-bucket   AWS              62c5604822125b72fac3f9b6
```

## Checklist

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added any necessary documentation in document requirements section listed in [CONTRIBUTING.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/CONTRIBUTING.md) (if appropriate)
- [x] I have addressed the @mongodb/docs-cloud-team comments (if appropriate)
- [x] I have updated [test/README.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/test/README.md) (if an e2e test has been added)
- [x] I have run `make fmt` and formatted my code

2022-07-07 13:29 UTC, sarahsimpers requested changes
Just a few small changes, thanks!

2022-07-07 13:29 UTC, sarahsimpers commented on docs/atlascli/command/atlas-backups-exports-buckets-describe.txt
> +Retrieve one snapshot export bucket.
Nit: changing for consistency with the language we use now for API
```suggestion
Return one snapshot export bucket.
```

2022-07-07 13:29 UTC, sarahsimpers commented on docs/atlascli/command/atlas-backups-exports-buckets-describe.txt
> +   The following example retrieves the continuous backup export bucket specified by ID:
```suggestion
   The following example returns the continuous backup export bucket specified by the ID:
```

2022-07-07 13:35 UTC, Razeer123 commented on docs/atlascli/command/atlas-backups-exports-buckets-describe.txt
> +     - Unique identifier of the bucket
It's assigned by Atlas.

2022-07-07 13:43 UTC, sarahsimpers approved these changes

2022-07-08 09:00 UTC, fmenezes approved these changes
LGTM

2022-07-08 09:01 UTC, merged