CLOUDP-126263: Create command “atlas backups exports jobs describe”
mongodb/mongodb-atlas-cli pull request #1355
Opened 2022-07-07 11:17 UTC by fmenezes

## Proposed changes

_Jira ticket:_ CLOUDP-#

Closes #[issue number]

## Checklist

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added any necessary documentation in document requirements section listed in [CONTRIBUTING.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/CONTRIBUTING.md) (if appropriate)
- [ ] I have addressed the @mongodb/docs-cloud-team comments (if appropriate)
- [ ] I have updated [test/README.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/test/README.md) (if an e2e test has been added)
- [ ] I have run `make fmt` and formatted my code

## Further comments

2022-07-07 13:35 UTC, sarahsimpers requested changes
Just one copy change and a place where it appears to be the wrong description

2022-07-07 13:35 UTC, sarahsimpers commented on docs/atlascli/command/atlas-backups-exports-jobs-describe.txt
> +     - Unique identifier of the role that Atlas can use to access the bucket.
This seems like the wrong description here (or it's the wrong flag on line 35)

2022-07-07 13:37 UTC, sarahsimpers commented on docs/atlascli/command/atlas-backups-exports-jobs-describe.txt
> +Describe cloud backup export job for your project, cluster and bucket.
Oops not sure why this didn't come through with the last review
```suggestion
Return all cloud backup export jobs for your project, cluster, and bucket.
```

2022-07-08 11:37 UTC, drinkbird submitted a review, later dismissed

2022-07-08 18:29 UTC, sarahsimpers submitted a review, later dismissed

2022-07-11 09:03 UTC, gssbzn approved these changes
LGTM

2022-07-11 09:07 UTC, merged