DOCSP-26387 added a mongocli  backup list example
mongodb/mongodb-atlas-cli pull request #1519
Opened 2022-11-08 16:31 UTC by kyuan-mongodb

## Proposed changes

_Jira ticket:_ DOCSP-26387

Closes #[issue number]

## Checklist

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added any necessary documentation in document requirements section listed in [CONTRIBUTING.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/CONTRIBUTING.md) (if appropriate)
- [ ] I have addressed the @mongodb/docs-cloud-team comments (if appropriate)
- [ ] I have updated [test/README.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/test/README.md) (if an e2e test has been added)
- [x] I have run `make fmt` and formatted my code

## Further comments

2022-11-08 18:12 UTC, andreaangiolillo commented on go.sum
> +cloud.google.com/go/asset v1.7.0/go.mod h1:YbENsRK4+xTiL+Ofoj5Ckf+O17kJtgp3Y3nn4uzZz5s=
you should not change this file

2022-11-08 18:12 UTC, andreaangiolillo commented on internal/cli/atlas/backup/snapshots/list.go
> +	"fmt"
the file is not formatted. Lint is failing. Run `make lint` to validate against our linting rules.

2022-11-08 19:59 UTC, andreaangiolillo commented on internal/cli/atlas/backup/snapshots/list.go
> +		  %s atlas backups snapshots list myDemo --output json`, cli.ExampleAtlasEntryPoint()),
```suggestion
		  %s backups snapshots list myDemo --output json`, cli.ExampleAtlasEntryPoint()),
```

2022-11-09 09:07 UTC, andreaangiolillo approved these changes
LGTM

2022-11-09 16:27 UTC, sarahsimpers requested changes

2022-11-09 16:27 UTC, sarahsimpers commented on internal/cli/atlas/backup/snapshots/list.go
> +		  %s backups snapshots list myDemo --output json`, cli.ExampleAtlasEntryPoint()),
Adjust spacing- should be two spaces indented (not from "Example" but from the start of the line)
```suggestion
  %s backups snapshots list myDemo --output json`, cli.ExampleAtlasEntryPoint()),
```

2022-11-10 19:36 UTC, sarahsimpers approved these changes
LGTM!

2022-11-10 19:37 UTC, merged