CLOUDP-163786: Add command "serverless backups snapshots list"
mongodb/mongodb-atlas-cli pull request #1724
Opened 2023-03-01 17:17 UTC by fmenezes

## Proposed changes

_Jira ticket:_ CLOUDP-#

Closes #[issue number]

## Checklist

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added any necessary documentation in document requirements section listed in [CONTRIBUTING.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/CONTRIBUTING.md) (if appropriate)
- [ ] I have addressed the @mongodb/docs-cloud-team comments (if appropriate)
- [ ] I have updated [test/README.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/test/README.md) (if an e2e test has been added)
- [ ] I have run `make fmt` and formatted my code

## Further comments

2023-03-01 18:02 UTC, gssbzn commented on internal/store/cloud_provider_backup_serverless.go
> +	case config.CloudService, config.CloudGovService:
I think gov doesn't support serverless

2023-03-01 18:03 UTC, gssbzn commented on internal/cli/atlas/serverless/backup/snapshots/list.go
> +  %s backups snapshots list myDemo --output json`, cli.ExampleAtlasEntryPoint()),
```suggestion
  %s serverless snapshots list myDemo --output json`, cli.ExampleAtlasEntryPoint()),
```

2023-03-01 18:03 UTC, gssbzn commented on internal/cli/atlas/serverless/backup/snapshots/list.go
> +		Example: fmt.Sprintf(`  # Return a JSON-formatted list of snapshots for the cluster named myDemo
```suggestion
		Example: fmt.Sprintf(`  # Return a JSON-formatted list of snapshots for the instance named myDemo 
```
I think we prefer instance when talking about serverless

2023-03-01 18:05 UTC, gssbzn commented on internal/cli/atlas/serverless/backup/snapshots/list_test.go
> +// Copyright 2020 MongoDB Inc
```suggestion
// Copyright 2023 MongoDB Inc
```

2023-03-01 18:06 UTC, gssbzn commented on internal/cli/atlas/serverless/backup/snapshots/list.go
> +// Copyright 2020 MongoDB Inc
```suggestion
// Copyright 2023 MongoDB Inc
```

2023-03-01 18:06 UTC, gssbzn commented on internal/cli/atlas/serverless/backup/backup_test.go
> +// Copyright 2022 MongoDB Inc
```suggestion
// Copyright 2023 MongoDB Inc
```

2023-03-01 18:06 UTC, gssbzn commented on internal/cli/atlas/serverless/backup/backup.go
> +// Copyright 2020 MongoDB Inc
```suggestion
// Copyright 2023 MongoDB Inc
```

2023-03-02 11:41 UTC, sarahsimpers requested changes
Small copy nitpicks. Thank you for including the required role! :)

2023-03-02 11:41 UTC, sarahsimpers commented on internal/cli/atlas/serverless/backup/snapshots/list.go
> +		Short:   "Return all cloud backup snapshots for your project and serverless instance.",
```suggestion
		Short:   "Return all cloud backup snapshots for the specified serverless instance in your project.",
```

2023-03-02 11:41 UTC, sarahsimpers commented on internal/cli/atlas/serverless/backup/snapshots/list.go
> +			"clusterNameDesc": "Name of the Atlas serverless instance that contains the snapshots you want to retrieve.",
```suggestion
			"clusterNameDesc": "Label that identifies the Atlas serverless instance that contains the snapshots you want to return.",
```

2023-03-02 11:47 UTC, sarahsimpers approved these changes
LGTM, thanks!

2023-03-02 12:04 UTC, gssbzn approved these changes
LGTM

2023-03-02 12:57 UTC, wtrocki approved these changes

2023-03-02 13:02 UTC, merged