CLOUDP-167790: Migrate Maintenance Windows CLI stores to v2 sdk
mongodb/mongodb-atlas-cli pull request #1834
Opened 2023-04-04 14:18 UTC by swattyT

## Proposed changes

_Jira ticket:_ CLOUDP-# [CLOUDP-167790](https://jira.mongodb.org/browse/CLOUDP-167790)
EVG Patch: https://spruce.mongodb.com/version/642c31ad850e61fcf29ddb68/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

Closes #[issue number]

## Checklist

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added any necessary documentation in document requirements section listed in [CONTRIBUTING.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/CONTRIBUTING.md) (if appropriate)
- [ ] I have addressed the @mongodb/docs-cloud-team comments (if appropriate)
- [ ] I have updated [test/README.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/test/README.md) (if an e2e test has been added)
- [x] I have run `make fmt` and formatted my code

## Further comments

2023-04-04 14:20 UTC, swattyT reviewed
Manual Testing:

➜  mongodb-atlas-cli git:(CLOUDP-167790) ✗ bin/atlas maintenanceWindows update --dayOfWeek 1 --hourOfDay 1 --projectId 6421987cdc060f20518edb62 --debug
2023/04/04 15:10:45 
PATCH /api/atlas/v2/groups/6421987cdc060f20518edb62/maintenanceWindow HTTP/1.1
Host: cloud-dev.mongodb.com
User-Agent: atlascli/1.6.0-35-gc0ee57c1 (darwin;arm64)
Content-Length: 48
Accept: application/vnd.atlas.2023-01-01+json
Content-Type: application/vnd.atlas.2023-01-01+json
Accept-Encoding: gzip

{"dayOfWeek":1,"hourOfDay":1,"startASAP":false}

2023/04/04 15:10:45 
HTTP/1.1 200 OK
Content-Length: 0
Date: Tue, 04 Apr 2023 14:10:45 GMT
Referrer-Policy: strict-origin-when-cross-origin
Server: mdbws
Strict-Transport-Security: max-age=31536000; includeSubdomains;
X-Content-Type: application/vnd.atlas.2023-01-01+json
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Java-Method: ApiAtlasGroupMaintenanceWindowResource::patchGroupMaintenanceWindows
X-Mongodb-Service-Version: gitHash=8322f2c696bc5a77736508e04b70ff0249607cfe; versionString=master
X-Permitted-Cross-Domain-Policies: none


Maintenance window updated.
telemetry: events: [{2023-04-04 15:09:25.897739 +0100 IST atlascli map[arch:arm64 auth_method:api_key command:atlas-maintenanceWindows-update error:unknown flag: --dayofWeek git_commit:c0ee57c133a01a0a514c1ccee04b719a66aac9d0 ops_manager_url:https://cloud-dev.mongodb.com/ org_id:6267ff7d1c7668600097c21d os:darwin profile:default result:ERROR service:cloud terminal:tty version:1.6.0-35-gc0ee57c1]} {2023-04-04 15:10:24.378751 +0100 IST atlascli map[arch:arm64 auth_method:api_key command:atlas-maintenanceWindows-update error:unknown flag: --dayofWeek git_commit:c0ee57c133a01a0a514c1ccee04b719a66aac9d0 ops_manager_url:https://cloud-dev.mongodb.com/ org_id:6267ff7d1c7668600097c21d os:darwin profile:default result:ERROR service:cloud terminal:tty version:1.6.0-35-gc0ee57c1]} {2023-04-04 15:10:46.072677 +0100 IST m=+2.102740918 atlascli map[alias:update arch:arm64 auth_method:api_key command:atlas-maintenanceWindows-update duration:2077 flags:[dayOfWeek debug hourOfDay projectId] git_commit:c0ee57c133a01a0a514c1ccee04b719a66aac9d0 ops_manager_url:https://cloud-dev.mongodb.com/ org_id:6267ff7d1c7668600097c21d os:darwin profile:default project_id:6421987cdc060f20518edb62 result:SUCCESS service:cloud terminal:tty version:1.6.0-35-gc0ee57c1]}]
request:
POST https://cloud-dev.mongodb.com/api/private/v1.0/telemetry/events
response:
HTTP/1.1 202 Accepted
Vary: Accept-Encoding
Date: Tue, 04 Apr 2023 14:10:46 GMT
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Java-Method: TelemetryResource::events
X-Mongodb-Service-Version: gitHash=8322f2c696bc5a77736508e04b70ff0249607cfe; versionString=master
Content-Length: 0
Server: mdbws
Strict-Transport-Security: max-age=31536000; includeSubdomains;
Referrer-Policy: strict-origin-when-cross-origin
X-Permitted-Cross-Domain-Policies: none


➜  mongodb-atlas-cli git:(CLOUDP-167790) ✗ bin/atlas maintenanceWindows describe -o json --projectId 6421987cdc060f20518edb62
{
  "autoDeferOnceEnabled": false,
  "dayOfWeek": 1,
  "hourOfDay": 1,
  "startASAP": false
}
➜  mongodb-atlas-cli git:(CLOUDP-167790) ✗ bin/atlas maintenanceWindows describe --projectId 6421987cdc060f20518edb62 
DAY OF THE WEEK   HOUR OF DAY   START ASAP
1                 1             false
➜  mongodb-atlas-cli git:(CLOUDP-167790) ✗ bin/atlas maintenanceWindows clear  --projectId 6421987cdc060f20518edb62
? Are you sure you want to delete: maintenance window Yes
Maintenance window removed.

2023-04-04 14:25 UTC, wtrocki requested changes
LGTM (but let's not merge to v2client branch until lands to master)

2023-04-06 11:50 UTC, matt-condon approved these changes
LGTM

2023-04-06 15:10 UTC, wtrocki approved these changes

2023-04-06 16:48 UTC, merged