CLOUDP-167770: migrate 'alerts' CLI stores to v2 sdk
mongodb/mongodb-atlas-cli pull request #1926
Opened 2023-05-03 13:45 UTC by matt-condon

## Proposed changes

_Jira ticket:_ CLOUDP-167770

Migration to sdkv2 of AlertDescriber, AlertLister, AlertAcknowledger

Currently blocked by ReplicaSetEventTypeViewForNdsGroupAlertable allowed values limitation (WIP)

## Checklist

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added any necessary documentation in document requirements section listed in [CONTRIBUTING.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/CONTRIBUTING.md) (if appropriate)
- [ ] I have addressed the @mongodb/docs-cloud-team comments (if appropriate)
- [ ] I have updated [test/README.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/test/README.md) (if an e2e test has been added)
- [x] I have run `make fmt` and formatted my code

2023-05-29 08:31 UTC, fmenezes commented on .DS_Store
maybe delete this file?

2023-05-29 13:51 UTC, fmenezes commented on internal/cli/atlas/alerts/list.go
> -		ListOptions: *opts.NewListOptions(),
have we stopped paginating?

2023-05-29 13:53 UTC, gssbzn approved these changes
LGTM thanks

2023-05-29 13:56 UTC, fmenezes requested changes
I see flags for pageNum and no data being passed to the store, can you confirm if we are indeed paginating or not for the list command?

2023-05-29 16:21 UTC, matt-condon commented
> I see flags for pageNum and no data being passed to the store, can you confirm if we are indeed paginating or not for the list command?

Thanks for flagging @fmenezes 
I amended the approach for this PR to use structs, and included the listOptions

2023-05-29 16:32 UTC, wtrocki commented on internal/cli/atlas/alerts/list_test.go
> +				Id:            pointer.Get("test"),
[Unrelated] We need to document SDK methods that create integer or string pointers so users can use SDK without having to rely on pointer lib etc.

2023-05-29 16:32 UTC, wtrocki approved these changes

2023-05-29 16:59 UTC, wtrocki commented on internal/cli/atlas/alerts/list_test.go
> +				Id:            pointer.Get("test"),
creating jira

2023-06-02 10:08 UTC, wtrocki approved these changes

2023-06-02 12:50 UTC, fmenezes approved these changes

2023-06-02 12:51 UTC, swattyT approved these changes
LGTM!

2023-06-02 12:58 UTC, merged