CLOUDP-179038 Add tags flag to atlas clusters create/update/upgrade
mongodb/mongodb-atlas-cli pull request #1968
Opened 2023-05-29 13:31 UTC by fmenezes

## Proposed changes

Add tags flag to atlas clusters create/update/upgrade

_Jira ticket:_ CLOUDP-179038

## Checklist

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added any necessary documentation in document requirements section listed in [CONTRIBUTING.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/CONTRIBUTING.md) (if appropriate)
- [ ] I have addressed the @mongodb/docs-cloud-team comments (if appropriate)
- [ ] I have updated [test/README.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/test/README.md) (if an e2e test has been added)
- [ ] I have run `make fmt` and formatted my code

## Further comments

2023-05-29 13:54 UTC, gssbzn commented on docs/atlascli/command/atlas-clusters-create.txt
> +     - stringToString
🤔 this may need an update on https://github.com/mongodb-labs/cobra2snooty

2023-05-29 13:54 UTC, gssbzn commented on go.sum
> +go.mongodb.org/atlas v0.26.2-0.20230529122338-7389eac5a4dd h1:yXAJNFz8e93a1OzxPZ3jYXzne99N1wFnewuuO15IM/I=
can you do a release of the SDK and ping here now to the stable branch to get back dependabot?

2023-05-29 13:55 UTC, gssbzn approved these changes

2023-05-29 15:46 UTC, gssbzn approved these changes
LGTM

2023-05-29 18:15 UTC, wtrocki submitted a review, later dismissed

2023-05-30 15:29 UTC, jwilliams-mongo commented on internal/usage/usage.go
> +	UpdateTag                                 = Tag + " This will replace existing tags."
per style guide, use present tense where possible: https://www.mongodb.com/docs/meta/style-guide/writing/use-present-tense/
```suggestion
	UpdateTag                                 = Tag + " This replaces existing tags."
```

2023-05-30 15:29 UTC, jwilliams-mongo commented on internal/usage/usage.go
> +	Tag                                       = "Collection of key-value pairs that categorizes the cluster."
how are these delimited?

2023-05-30 15:46 UTC, fmenezes commented on internal/usage/usage.go
> +	Tag                                       = "Collection of key-value pairs that categorizes the cluster."
`--tag key=value,key2=value2` OR `--tag key=value --tag key2=value2`

2023-05-31 13:52 UTC, jwilliams-mongo approved these changes
@fmenezes left one suggestion for the description of tag to better guide users in the case where they want to add multiple tags. LGTM otherwise

2023-05-31 14:08 UTC, corryroot requested changes
I commented with my copy suggestions, which should align with the OpenAPI annotations.

2023-05-31 14:08 UTC, corryroot commented on docs/atlascli/command/atlas-clusters-create.txt
> +     - Collection of key-value pairs that categorizes the cluster. This value defaults to [].
```suggestion
     - List that contains key-value pairs between 1 to 255 characters in length for tagging and categorizing the cluster. This value defaults to [].
```

2023-05-31 14:08 UTC, corryroot commented on docs/atlascli/command/atlas-clusters-update.txt
> +     - Collection of key-value pairs that categorizes the cluster. Passing this flag replaces preexisting data. This value defaults to [].
```suggestion
     - List that contains key-value pairs between 1 to 255 characters in length for tagging and categorizing the cluster. Passing this flag replaces preexisting data. This value defaults to [].
```

2023-05-31 14:08 UTC, corryroot commented on docs/atlascli/command/atlas-clusters-upgrade.txt
> +     - Collection of key-value pairs that categorizes the cluster. Passing this flag replaces preexisting data. This value defaults to [].
```suggestion
     - List that contains key-value pairs between 1 to 255 characters in length for tagging and categorizing the cluster. Passing this flag replaces preexisting data. This value defaults to [].
```

2023-05-31 14:08 UTC, corryroot commented on docs/mongocli/command/mongocli-atlas-clusters-create.txt
> +     - Collection of key-value pairs that categorizes the cluster. This value defaults to [].
```suggestion
     - List that contains key-value pairs between 1 to 255 characters in length for tagging and categorizing the cluster. This value defaults to [].
```

2023-05-31 14:08 UTC, corryroot commented on docs/mongocli/command/mongocli-atlas-clusters-update.txt
> +     - Collection of key-value pairs that categorizes the cluster. Passing this flag replaces preexisting data. This value defaults to [].
```suggestion
     - List that contains key-value pairs between 1 to 255 characters in length for tagging and categorizing the cluster. Passing this flag replaces preexisting data. This value defaults to [].
```

2023-05-31 14:39 UTC, corryroot submitted a review, later dismissed
LGTM!

2023-06-01 09:18 UTC, andreaangiolillo approved these changes

2023-06-01 09:18 UTC, andreaangiolillo approved these changes

2023-06-01 09:27 UTC, merged