DOCSP-27556 atlas accesslogs list example
mongodb/mongodb-atlas-cli pull request #2083
Opened 2023-07-12 17:54 UTC by kyuan-mongodb

## Proposed changes

Added an example for atlas accesslogs list command.

_Jira ticket:_ DOCSP-27556

Closes #[issue number]

## Checklist

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added any necessary documentation in document requirements section listed in [CONTRIBUTING.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/CONTRIBUTING.md) (if appropriate)
- [ ] I have addressed the @mongodb/docs-cloud-team comments (if appropriate)
- [ ] I have updated [test/README.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/test/README.md) (if an e2e test has been added)
- [x] I have run `make fmt` and formatted my code

## Further comments

2023-07-12 18:13 UTC, melissamahoney-mongodb requested changes

2023-07-12 18:13 UTC, melissamahoney-mongodb commented on internal/cli/atlas/accesslogs/list.go
> +		Example: fmt.Sprintf(`  # Return a JSON-formatted list of all access list entries for the project with ID 618d48e05277a606ed2496fe for the cluster named Cluster0:
Change: This isn't quite right. These aren't access list entries, they are a list of authentication requests made against the cluster. See: https://www.mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/Access-Tracking/operation/listAccessLogsByClusterName

2023-07-13 10:35 UTC, gssbzn approved these changes

2023-07-17 15:49 UTC, melissamahoney-mongodb approved these changes

2023-07-17 15:49 UTC, merged