DOCSP-31899 Update docs for Creating an export bucket to s3
mongodb/mongodb-atlas-cli pull request #2147
Opened 2023-08-09 17:54 UTC by kanchana-mongodb

## Proposed changes

Update docs for Creating an export bucket to s3. Specifically, add link to Atlas docs where we describe how to create and retrieve Cloud Provider role access for Atlas.

_Jira ticket:_ DOCSP-31899

Closes #[issue number]

## Checklist

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added any necessary documentation in document requirements section listed in [CONTRIBUTING.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/CONTRIBUTING.md) (if appropriate)
- [ ] I have addressed the @mongodb/docs-cloud-team comments (if appropriate)
- [ ] I have updated [test/README.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/test/README.md) (if an e2e test has been added)
- [ ] I have run `make fmt` and formatted my code

## Further comments

2023-08-09 18:08 UTC, sarahsimpers submitted a review, later dismissed
LGTM with one small nit. Also, you may want to use a dochub URL here instead of the docs URL, but that's a non-blocking suggestion.

2023-08-09 18:08 UTC, sarahsimpers commented on internal/usage/usage.go
> +	ExportBucketIAMRoleID                     = "Unique identifier that Atlas assigns to the cloud provider access role for the bucket. To learn more about setting up and retrieving cloud provider acces
```suggestion
	ExportBucketIAMRoleID                     = "Unique identifier that Atlas assigns to the cloud provider access role for the bucket. To learn more about setting up and retrieving a cloud provider access role, see: https://www.mongodb.com/docs/atlas/security/set-up-unified-aws-access/."
```

2023-08-11 09:01 UTC, gssbzn commented
@kanchana-mongodb you need to regenerate the docs

2023-08-11 13:46 UTC, sarahsimpers requested changes

2023-08-11 13:46 UTC, sarahsimpers commented on internal/usage/usage.go
> +	ExportBucketIAMRoleID                     = "Unique identifier that Atlas assigns to the cloud provider access role for the bucket. To learn more about setting up and retrieving a cloud provider acc
Need to remove the trailing slash, I tried navigating to the URL and it doesn't work with the trailing slash
```suggestion
	ExportBucketIAMRoleID                     = "Unique identifier that Atlas assigns to the cloud provider access role for the bucket. To learn more about setting up and retrieving a cloud provider access role, see: https://dochub.mongodb.org/core/set-up-unified-aws-access."
```

2023-08-11 13:59 UTC, sarahsimpers approved these changes
LGTM, thanks!

2023-08-11 14:04 UTC, gssbzn approved these changes

2023-08-11 14:50 UTC, merged