CLOUDP-229357: docs correction for atlas deployment commands
mongodb/mongodb-atlas-cli pull request #2630
Opened 2024-02-12 18:55 UTC by tibulca

## Proposed changes

docs correction for atlas deployment commands

_Jira ticket:_ CLOUDP-229357

2024-02-12 19:48 UTC, andreaangiolillo approved these changes
LGTM

2024-02-13 09:37 UTC, gssbzn requested changes
can you rollback the chnages to the tests please

2024-02-13 12:10 UTC, andreaangiolillo approved these changes

2024-02-13 13:12 UTC, gssbzn approved these changes
thanks

2024-02-13 16:48 UTC, merged