CLOUDP-278912: Export without Fed Auth
mongodb/mongodb-atlas-cli pull request #3329
Opened 2024-10-16 09:07 UTC by josvazg

## Proposed changes

_Jira ticket:_ CLOUDP-278912

The Atlas CLI Kubernetes config export should not fail when there is no Federated Auth configured.

## Checklist

- [X] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added any necessary documentation in document requirements section listed in [CONTRIBUTING.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/CONTRIBUTING.md) (if appropriate)
- [ ] I have addressed the @mongodb/docs-cloud-team comments (if appropriate)
- [ ] I have updated [test/README.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/test/README.md) (if an e2e test has been added)
- [X] I have run `make fmt` and formatted my code

## Further comments

2024-10-16 09:23 UTC, helderjs requested changes

2024-10-16 09:23 UTC, helderjs commented on internal/kubernetes/operator/config_exporter.go
> +		if isAPIError(err, "RESOURCE_NOT_FOUND") {
Redundant new function. Please use `admin.IsErrorCode()`

2024-10-16 09:51 UTC, josvazg commented on internal/kubernetes/operator/config_exporter.go
> +		if isAPIError(err, "RESOURCE_NOT_FOUND") {
fixed

2024-10-16 10:05 UTC, helderjs approved these changes

2024-10-17 07:06 UTC, s-urbaniak approved these changes

2024-10-17 07:25 UTC, merged